### BONJOUR FRANÇOIS-ALEXIS, ICI JEAN-HUGUES ROY
### TOUS MES COMMENTAIRES SERONT EN MAJUSCULES ET PRÉCÉDÉS DE 3 # (HASHTAGS)

# coding : utf-8

# solution devoir 1

url = "https://montrealcampus.ca?p=" ### EXCELLENT DÉPART :)

l2 = list()
n = 20001
l2.append(str(n)) ### ICI, TA LISTE "l2" NE CONTIENT QU'UN SEUL ÉLÉMENT
 
article = l2 ### ICI, LES VARIABLES "article" ET "l2" SONT IDENTIQUES ET NE CONTIENNENT QU'UN SEUL ÉLÉMENT. ÉTAPE INUTILE, MALHEUREUSEMENT.
# print(article,l2)

for article in l2: ### OK, LA VARIABLE "article" VA ÊTRE ÉCRASÉE PAR LES ÉLÉMENTS DE LA LISTE "l2"...
   n = n+1
   l2.append(str(n)) ### TU AS TROUVÉ UNE FAÇON TRÈS INTÉRESSANTE DE PROCÉDER, MAIS CE FAISANT, TU CRÉES UNE BOUCLE SANS FIN...
#    print(l2)
   print(url[0:28]+str(article)) ### TRÈS BIEN, TU CRÉES LES URLS RECHERCHÉS. IL N'EST PAS NÉCESSAIRE D'INDIQUER QUE TU PRENDS LES CARACTÈRES 0 À 27 DE LA VARIABLE "url" PUISQUE SA TAILLE EST JUSTEMENT DE 28 CARACTÈRES.
   if (int(n)) == 30151: ### AH! TU PRENDS DE L'AVANCE SUR LA MATIÈRE DU 2E COURS SUR PYTHON! :)
       break ### BONNE FAÇON DE QUITTER TA BOUCLE SANS FIN; MAIS CE N'EST GÉNÉRALEMENT PAS UNE BONNE PRATIQUE QUE DE RECOURIR À UN "BREAK" SI ON PEUT PROCÉDER AUTREMENT.
# print(len(l2))

### TU ES PRÈS DU BUT!
### JE VOUS DEMANDAIS DE PLACER TOUTES LES URLS QUE VOTRE SCRIPT GÉNÈRE DANS UNE LISTE.
### ON VA DONC CRÉER CETTE LISTE:

toutesLesURL = []

### ON PEUT ENSUITE FAIRE UNE BOUCLE DANS UN "RANGE" QUI VA DE 20000 À 30150. ÇA PEUT ÊTRE TA VARIABLE "l2":

l2 = list(range(20000,30151))

### JE REPRENDS ICI LA BOUCLE QUE TU AS ÉCRITE:

for article in l2:

### À L'INTÉRIEUR DE LAQUELLE ON PEUT GÉNÉRER CHAQUE URL QU'ON CHERCHE UN PEU COMME TU L'AS FAIT:
    
    urlCampus = url + str(article)
    print(urlCampus) ### AFFICHAGE AUX FINS DE VÉRIF.

### CHAQUE FOIS QU'UN URL EST GÉNÉRÉ, ON L'AJOUTE À NOTRE LISTE "toutesLesURL":

    toutesLesURL.append(urlCampus)

### APRÈS QUE LA BOUCLE AIT FAIT SON TRAVAIL, ON AFFICHE NOTRE LISTE ET SA TAILLE POUR VÉRIFIER:

print(toutesLesURL, len(toutesLesURL)) ### BINGO!

### ENFIN, IL MANQUAIT DES COMMENTAIRES DANS TON CODE POUR QUE TU M'EXPLIQUES CE QUE TU SOUHAITAIS FAIRE.
